.PHONY: clean All

All:
	@echo "----------Building project:[ assign2 - Debug ]----------"
	@"$(MAKE)" -f  "assign2.mk"
clean:
	@echo "----------Cleaning project:[ assign2 - Debug ]----------"
	@"$(MAKE)" -f  "assign2.mk" clean
